src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(
 *     normalizationContext={"groups"={"user:read"}},
 *     denormalizationContext={"groups"={"user:write"}},
        collectionOperations={
 *         "get"={"security_message"="Only Boog can see all users."},
 *         "post",
 *     },
 *     itemOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN') or object == user","security_message"="Sorry, this is not you."},
 *         "put"={"security"="is_granted('ROLE_ADMIN') or object == user"},
 *         "delete"={"security"="is_granted('ROLE_ADMIN')"}
 *     }
 *
 * )
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups({"user:read", "user:write","order:read","order:write"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     *
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Groups({"user:write","order:write"})
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"user:read", "user:write","order:write","order:read"})
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Orders::class, mappedBy="user",cascade={"persist"})
     * @Groups({"user:read"})
     */
    private $orders;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Groups({"user:read", "user:write"})
     */
    private $isDeleted;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     * @Groups({"user:read", "user:write"})
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"user:read", "user:write"})
     */
    private $surname;

    /**
     *
     * @ORM\Column(type="string", length=255)
     */
    private $register;

    /**
     * @Groups({"user:read", "user:write","order:read","order:write"})
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Streetnumber;

    /**
     * @Groups({"user:read", "user:write","order:read","order:write"})
     * @ORM\ManyToOne(targetEntity=Postcode::class)
     */
    private $postcode;



    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Orders[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {

            $this->orders[] = $order;
            $order->setUser($this);



        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(?bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getRegister(): ?string
    {
        return $this->register;
    }

    public function setRegister(string $register): self
    {
        $this->register = $register;

        return $this;
    }

    public function getStreetnumber(): ?int
    {
        return $this->Streetnumber;
    }

    public function setStreetnumber(?int $Streetnumber): self
    {
        $this->Streetnumber = $Streetnumber;

        return $this;
    }

    public function getPostcode(): ?Postcode
    {
        return $this->postcode;
    }

    public function setPostcode(?Postcode $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}3DPrintFarm{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        {% endblock %}
    </head>
    <body>


    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">3DprintAdmin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ path('app_homepage') }}">Home </a>
                <a class="nav-item nav-link" href="{{ path('app_admin_objects') }}">Objects </a>
                <a  class="nav-item nav-link" href="{{ path('app_object_form') }}">Add object </a>
                <a  class="nav-item nav-link" href="{{ path('app_admin_orders') }}">Orders </a>
                <a  class="nav-item nav-link" href="{{ path('app_order_form') }}">Add order </a>
                <a class="nav-item nav-link" href="{{ path('app_logout') }}">Logout</a>
            </div>
        </div>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <p class="text-light">Admin: {{ app.user.email }}</p>
        {% endif %}
    </nav>


        {% block body %}



        {% endblock %}

        {% block main %}{% endblock %}
        {% block javascripts %}
            <script
                    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                    integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
                    crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


        {% endblock %}
    </body>
</html>

templates/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
    </div>
    <div id="root" class="bg-light"></div>
<div class="row">
    <div class="col mt-5">
        <div class="card">
            <img
                    class="card-image-top"
                    src="http://192.168.0.134:8080/?action=snapshot"
                    alt='Webcam disabled'
                    width="250"
            />
            <div class='card-body'>

                <ul>
                    <li>
                        Printer up:
                        <strong>Operational</strong>
                    </li>
                    <li>
                        SD card ready:
                        <strong>Ready</strong>
                    </li>
                    <li>
                        Bed temperature:
                        <strong>44</strong>
                    </li>
                    <li>
                        Hotend temp:
                        <strong>195</strong>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <div class="col mt-5">
        <div class="card">
            <img
                    class="card-image-top"
                    src="http://192.168.0.134:8080/?action=snapshot"
                    alt='Webcam disabled'
                    width="250"
            />
            <div class='card-body'>

                <ul>
                    <li>
                        Printer up: <strong>Operational</strong>
                    </li>
                    <li>
                        SD card ready:
                        <strong>Ready</strong>
                    </li>
                    <li>
                        Bed temperature:
                        <strong>50</strong>
                    </li>
                    <li>
                        Hotend temp:
                        <strong>201</strong>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <div class="col mt-5">
        <div class="card">
            <img
                    class="card-image-top"
                    src="http://192.168.0.134:8080/?action=snapshot"
                    alt='Webcam disabled'
                    width="250"
            />
            <div class='card-body'>

                <ul>
                    <li>
                        Printer up: <strong>Operational</strong>
                    </li>
                    <li>
                        SD card ready:
                        <strong>Ready</strong>
                    </li>
                    <li>
                        Bed temperature:
                        <strong>27</strong>
                    </li>
                    <li>
                        Hotend temp:
                        <strong>27</strong>
                    </li>
                </ul>

            </div>
        </div>
    </div>

</div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">
        var initialAppState = {{ printers_serialized | raw }} ;
    </script>
    {{ encore_entry_script_tags("app") }}








{% endblock %}

templates/pdf.html.twig
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Invoice 3DPrintFarm </title>
</head>
<body>


<header style="background-color: #263238; width: 100%; height: 120px;  overflow: hidden;">
    <div style="display: flex;">
    <img src="https://wdev.be/wdev_arno/eindwerk/system/public/uploads/images/logo.png" alt='logo' style="display: block; width: 80px;">
    <div style="margin-left: 90px"><h1 style="color: floralwhite" >3D-Print-Domain </h1>
        <h4 style="color: floralwhite">Van idee naar Invoice</h4></div>

    <ul style="position: absolute; margin-left: 70%; color: floralwhite; font-size:12px; list-style: none; ">
        <li>3D-Print-Domain </li>
        <li>ValseStraat 32 </li>
        <li>3DprintAdmin</li>
        <li>070/245 245</li>
        <li>3Dprintdomaininfo@gmail.com</li>
    </ul>
    </div>
</header>
<hr>
<strong>{{ order.date | date ('d/m/Y')}}</strong><p>order: {{ orderid }}</p>
<br>
<br>

<h4>Name: </h4>
<p>{{ user.name }} {{ user.surname }}</p>
<h4>Adress:</h4>
<ul>
    <li>{{ user.address }} {{ user.streetnumber }}</li>

</ul>

<strong>{{ order.shippingadress }}</strong>
<h3> Products: </h3>




<table style="border: 1px solid black; width: 100%;">
    <tr style="border: 1px solid black; background: lightgrey">

        <th>
            Object Name:
        </th>



        <th>
            Amount:
        </th>


        <th>
            Price:
        </th>


        <th>
            Subtotal:
        </th>

    </tr>

    {% for detail in details %}


        <tr>

            <td>
                {{ detail.objects.name }}
            </td>

            <td>
                X  {{ detail.quantity }}
            </td>

            <td>
                {{ detail.objects.getFormattedPrice }}
            </td>


            <td>
                €{{ detail.quantity*detail.objects.getCurrentPriceValue | slice(0,-2)  }},{{ detail.quantity*detail.objects.getCurrentPriceValue | slice(-2)  }}
            </td>

        </tr>

    {% endfor %}
</table>
<strong> Total: </strong>

{% for detail in details %}
    {% set sum = detail.quantity*detail.objects.getCurrentPriceValue  + sum ?? 0 %}
    {% if loop.last %} €{{ sum | slice(0,-2) }}, {{ sum|slice(-2) }}{% endif %}
{% endfor %}

<br>
<br>
<hr>

Thank you for your purchase. See you soon!
<br><br><br>
Address:<br>
------------------------------------------------------------------------------------------



<br><br><br>




Aan de Heer/Mevr.
<br>
<br>

{% if order.shippingadress == false %}
    {{ user.name }} {{ user.surname }}<br>
    {{ user.address }} {{ user.streetnumber }} <br>
    {{ user.postcode.Postcode }} {{ user.postcode.plaatsnaam }} <br>
    {{ user.postcode.gemeente }}
    {% else %}
        {{ order.shippingadress }}

{% endif %}






</body>
</html>